apiVersion: v1
kind: Service
metadata:
  name: f5hello-world
  namespace: f5demo
  labels:
    app: f5hello-world
spec:
  ports:
  - name: f5hello-world
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: NodePort
  selector:
    app: f5hello-world